# Generated by Django 5.1.4 on 2024-12-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='criado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_user': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios_criados', to='estoque.usuario'),
        ),
    ]
