# Generated by Django 5.1.4 on 2024-12-23 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_usuario_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='admin_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.usuario'),
        ),
    ]
