# Generated by Django 5.1.4 on 2024-12-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_produto_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='cnpj',
        ),
    ]
