# Generated by Django 5.1.4 on 2024-12-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_fornecedor_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.IntegerField(default=1234, max_length=13),
        ),
    ]
