# Generated by Django 5.1.4 on 2024-12-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_produto_codigo_de_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentoestoque',
            name='fornecedor',
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.IntegerField(default=1234),
        ),
    ]
